### ISSUE TITLE
Kpcre not build and not compile in Debian 11 (Bullseye)

### ISSUE THREAD

**Issue by EagletUSSR** [smcho-kr/kpcre#33]
Hello, friend!

I hope that the letter has been sent by me to the correct address and it will reach you. I have been using your development kpcre for iptables for several years now. Thank you very much for your work. But now there is a problem: in the latest version of Debian 11 (Bullseye), your development refuses to build and compile. Please, if you have the time and opportunity, update your project code at https://github.com/xnsystems/kpcre.git so that your development can work in the latest version of Debian 11 (Bullseye). I understand that you are most likely a very busy person, but I am not a programmer, but a system administrator and I have no one else to turn to except you. I hope that you will respond to my request and can take the time to solve the problem with kpcre with the latest Linux kernels. I would be glad to talk with you on other topics as well, I have many-sided interests in the field of information technology. I would be glad to receive your answer to my letter.

**Comment by smcho-kr** [comment]
Well, it's harder to fix than I thought it would be.
The new kernel doesn't export the memory allocation functions that suit my needs. :(
I think my module can't be compiled without modifying the vanilla kernel.
The necessary modification is just adding a single line to the kernel, though.

**Comment by EagletUSSR** [comment]
Thank you so much for your work. I received your letter today. Can you submit a commit to the vanilla Linux kernel to make the change you want? Your project is very important not only to me, and I would very much like your iptables module to work in modern Linux kernels.

**Comment by EagletUSSR** [comment]
I can ask some of my acquaintances from former Debian developers to commit the patch to the vanilla linux kernel so that it will appear in Debian during the last update.

**Comment by EagletUSSR** [comment]
Please post the required patch for the vanilla Linux kernel. I'll send it to the developers then or you can try it yourself.

**Comment by smcho-kr** [comment]
If the new kernel exported "__vmalloc_node_range()", it would be easy to fix the problem.
I need a legitimate function in which I can specify the protection mask for the allocated pages.

**Comment by EagletUSSR** [comment]
> If the new kernel exported "__vmalloc_node_range()", it would be easy to fix the problem.
> I need a legitimate function in which I can specify the protection mask for the allocated pages.

Please provide your more detailed explanation so that I could send this technical information of yours to the Linux kernel developers.

**Comment by smcho-kr** [comment]
I need to allocate **executable pages** inside a kernel module.
In older kernels,  "__vmalloc()" accepts a parameter which is for the protection mask.
By specifying "PAGE_KERNEL_EXEC" as the protection mask, I was able to allocate executable pages inside a kernel module.
In the new kernel, they changed "__vmalloc()" and it doesn't take the protection mask parameter anymore.
If the new kernel exported "__vmalloc_node_range()" which accepts the protection mask, I would be able to get executable pages inside a kernel module.

EXPORT_SYMBOL(__vmalloc_node_range);

Adding the above single line in "mm/vmalloc.c" is all it takes to enable the allocation of executable pages inside a kernel module.

**Comment by smcho-kr** [comment]
I discovered that "From the 5.8 kernel, the __vmalloc() function's third parameter -  pgprot_t prot - has been removed (as the kernel developers thought there weren't any users for page permissions besides the usual ones."
Obviously, they didn't know my PCRE module. :)

Anyway, the modules now can be compiled on the new kernels. (>= 5.8.0)
**YOU MUST USE ts_regex MODLUE**, not ts_pcre module which needs executable pages for JIT.
Although ts_pcre is compiled, your system will **CRASH** if you use ts_pcre module.

**Comment by EagletUSSR** [comment]
> I discovered that "From the 5.8 kernel, the __vmalloc() function's third parameter - pgprot_t prot - has been removed (as the kernel developers thought there weren't any users for page permissions besides the usual ones."
> Obviously, they didn't know my PCRE module. :)
> 
> Anyway, the modules now can be compiled on the new kernels. (>= 5.8.0)
> **YOU MUST USE ts_regex MODLUE**, not ts_pcre module which needs executable pages for JIT.
> Although ts_pcre is compiled, your system will **CRASH** if you use ts_pcre module.

Thank you very much for your work, for your responsiveness and care. Your development is very important for the security of my servers. I think it will be important for other people as well.
